# Generated by Django 5.0.1 on 2024-05-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=200)),
                ('country', models.CharField(default=1, max_length=200)),
                ('description', models.TextField(default='')),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Beach', 'Beach'), ('Mountain', 'Mountain'), ('City', 'City'), ('Historical', 'Historical')], default='Beach', max_length=100)),
                ('image_url', models.ImageField(default='default_image.jpg', upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
